- VBN Editor/GUI/MainForm.cs
This fix allows users living in regions outside of the US to import .anim files without problem.
> Fixed a regional issue

- VBN Editor/Filetypes/UI/LM.cs
- VBN Editor/Filetypes/UI/Texlist.cs
- VBN Editor/VBN Editor.csproj
I'm new to this c# wankery, so I'm sure there's a few stylistic faux pas.
"It's better than nothing"
> Add LM and texlist.lst parsers

- Smash Forge/GUI/About.Designer.cs
- Smash Forge/GUI/Editors/NUTEditor.Designer.cs
- Smash Forge/GUI/Editors/NUTEditor.cs
- Smash Forge/GUI/MainForm.Designer.cs
- Smash Forge/GUI/MainForm.cs
Because I wanted it.
They do work, I just didn't include that in the second commit message.
I haven't done any extensive testing though so there might still be bugs.
> Add remove button & clear all button to NUT editor

- Smash Forge/Filetypes/Models/NUD.cs
Fixes UV animations for .MTA files.
> Fix MTA UV animations

- Smash Forge/Filetypes/Melee/DAT.cs
- Updated map_head logic to skip invalid JOBJ offsets
> Fix invalid JOBJ acces in stage loading

- Smash Forge/Filetypes/Melee/DAT.cs
- Updated POBJ face index logic to use vertex list Count value directly instead of using IndexOf
> POBJ face index performance fix

- Smash Forge/Filetypes/Melee/DAT.cs
- Updated logic to check JOBJ flags to determine valid child and DOBJ offsets
- Updated logic to check POBJ flags to determine weight list processing
- Refactor weight list gathering outside of attribute processing loop
- Added initial variable to store max supported weight count (some stages use upwards of 12 weights per vertex)
TODO:
- Update shader logic to allow for more than 4 weights per vertex
> Update to fix dat file loading:

- Smash Forge/CharacterParamManager.cs
- Smash Forge/GUI/Editors/RenderTools.cs
- Smash Forge/GUI/Editors/VBNViewport.cs
- Smash Forge/GUI/MainForm.Designer.cs
- Smash Forge/GUI/MainForm.cs
- Smash Forge/GUI/Menus/RenderSettings.Designer.cs
- Smash Forge/GUI/Menus/RenderSettings.cs
- Smash Forge/Runtime.cs
- Smash Forge/Smash Forge.csproj
- Added fighter_param_vl_fighter.bin parameter file loading (Reads moves FAF/intangibility, hurtboxes and ledge grabboxes for now)
- Added hurtbox visualization
- Fixed grabboxes not being extended when visualized
- Added another grabbox event (Note: it requires changing SALT's PARAM_FORMAT event values to float)
- Added windbox flag read for special hitboxes
> Add figher parameter loading for hurtbox visualization

- Smash Forge/ACMDScriptManager.cs
- Smash Forge/GUI/Editors/RenderTools.cs
- Smash Forge/GUI/Editors/VBNViewport.cs
- Smash Forge/GUI/MainForm.cs
- Smash Forge/GUI/Menus/RenderSettings.Designer.cs
- Smash Forge/GUI/Menus/RenderSettings.cs
- Smash Forge/MovesetManager.cs
- Smash Forge/Runtime.cs
Added drawing of interpolated hitboxes, and generally cleaned up the logic in the hitbox/hurtbox drawing portion of the code.
> Added rendering of interpolated hitboxes

- Smash Forge/GUI/Editors/VBNViewport.cs
- Smash Forge/MovesetManager.cs
Main use case was sweetspot and sourspot visualization.
> Added hitbox colouring based on rough kb estimates

- Smash Forge/GUI/Editors/VBNViewport.cs
- Smash Forge/GUI/MainForm.cs
- Smash Forge/Runtime.cs
> Fixed config.xml and Render.png saving when opening through File Association

- Smash Forge/GUI/Editors/LVD Editor/LVDEditor.Designer.cs
Moved a few options around to avoid overlapping objects, most noticeably in the Collision editor.
> LVD Editor UI Adjustments

- Smash Forge/GUI/Menus/MaterialSelector.cs
> Fixed Material Presets not loading from the executable directory

- Smash Forge/param_labels/fighter_param_vl_zelda.ini
Had a lot more but didn't save
> Committed "some" of zelda's  param labels

- Smash Forge/param_labels/item_gen_param.ini
- Smash Forge/param_labels/simple_cafe_param.ini
Added .ini item_gen_param.bin and updated .ini for simple_cafe_param.bin
> Test Push from Xuman

- Smash Forge/param_labels/fighter_param_common.ini
- Smash Forge/param_labels/item_gen_param.ini
- Smash Forge/param_labels/simple_cafe_param.ini
Small update to that fighter_param_common.ini
> Updated the fighter_param_common.ini

- Smash Forge/param_labels/item_common_param.ini
Added param label for item_common_param with a defined entry count to make it easier to navigate in the param editor.
> Added param label for Item_common_param

- Smash Forge/param_labels/stdat_Metroid.ini
- Smash Forge/param_labels/stdat_Windyhill.ini
Added param names for Windmill speed on Windy Hill, and Ridley timers on Pyrosphere.
> stdat_Windyhill.ini stdat_Metroid.ini

- Smash Forge/param_labels/stdat_StreetFighter_f.ini
Added new param labels file for Suzaku (normal), covers position values for breakable signs
> Added param labels for Suzaku

- Smash Forge/param_labels/stdat_StreetFighter_f.ini
Added additional documentation on breakable sign position values, added labels for all of Group 2, fixed errors in previous version.
> Updated Suzaku params

- Smash Forge/param_labels/fighter_param_vl_pikachu.ini
Almost all special move params labeled
> fighter_param_vl_pikachu (Groups 13-20)

- Smash Forge/GUI/Editors/LVD Editor/LVDEditor.Designer.cs
- Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
- Smash Forge/GUI/Editors/LVD Editor/LVDList.cs
- Smash Forge/Smash Forge.csproj
I have changed the position and size of a few UI elements in the LVD Editor, in order to fix the issue of potentially having some UI elements appear off-screen. I will probably end up making more changes and additions to the LVD Editor after this; at the moment I'm just getting this bug out of the way.
Also fixes some param label ini files not being included during program build.
> LVD UI tweaks/fixes

- Smash Forge/param_labels/kumite_param_cafe.ini
- Smash Forge/param_labels/ui_category_db.ini
- Smash Forge/param_labels/ui_item_switch_db.ini
- Smash Forge/param_labels/ui_movie_db.ini
Updated Kumite, Ui Movie, added UI Category and UI Item Switch
> 3rd times the charm....ini update

- Smash Forge/ACMDScript.cs
also actually check that Runtime.renderHitboxAngles is set before drawing
> 361+ angle hitbox rendering

- Smash Forge/param_labels/stdat_Cave.ini
Params for cart knockback, knockback angle and damage, as well as chest explosion damage.
> Cave stdat params for cart and chests

- Smash Forge/Smash Forge.csproj
- Smash Forge/param_labels/battle_object_param.ini
- Smash Forge/param_labels/fighter_param.ini
- Smash Forge/param_labels/sq_vs_melee_data.ini
battle_object, fighter_param, sq_vs_melee_data
> Param label updates

- Smash Forge/Filetypes/BFRES/BFRES_Main.cs
- Smash Forge/Filetypes/BFRES/Switch/BNTX.cs
- Smash Forge/Filetypes/BFRES/WiiU/FTEX.cs
- Smash Forge/Filetypes/Models/ModelContainer.cs
- Smash Forge/Filetypes/Models/VBN.cs
- Smash Forge/GUI/Editors/BFRES Editors/BfresMaterialEditor.cs
- Smash Forge/GUI/MainForm.cs
- Smash Forge/GUI/ModelViewport.cs
- Smash Forge/Shader/Bfres/BFRES.frag
- Smash Forge/Shader/Bfres/BFRES.vert
- Smash Forge/Shader/Bfres/BFRES_Botw.frag
- Smash Forge/Shader/Bfres/BFRES_Debug.frag
- Smash Forge/Shader/Bfres/BFRES_PBR.frag
- Smash Forge/Shader/Bfres/BFRES_utility.frag
This mainly cleans up shaders while also fixing some issues with errors and crashing. I've also implemented color IDs like NUD for later addition with mesh selection.
> Fix alot of issues with bfres and some improvements. 

- Smash Forge/Filetypes/Textures/DDS.cs
Adds preliminary support for DX10 DDS files.
> Added rough support for DX10 DDS
