Smash Forge/Filetypes/Melee/DAT.cs
Smash Forge/Shader.cs

Some graphics cards have limited uniform slots available, so a static uniform array can possibly use them all. Update shader code to use UBO for bones array in order to save uniform slots.  Delay shader creation until after bone processing so that array size can be set to the proper size.
- Added output of shader program errors
- Changed bones uniform into UBO to avoid using up more uniform slots than necessary
- Changed vertex shader string to include formatting for bone count value replacement

Use Uniform Buffer Objects for bones

---

Smash Forge/Filetypes/Melee/DAT.cs
Smash Forge/IO/FileData.cs

The relocation table should be used to determine which offsets within the DAT file are valid by updating them during header processing with the proper address/offset as there can be relevant data located at the beginning of the data block.
- Added temporary change to FileData to support writing to data buffer (will probably refactor this class at some point in the future)
- Updated DAT logic to update all relocation table offsets appropriately
- Removed all unnecessary references to headerSize/0x20 as an offset

Use Relocation Table to determine valid offsets

---

Smash Forge/GUI/Editors/VBNViewport.cs

- Added command grabboxes visualization
- Fixed acmd handle not working for characters with non-angled ftilt/fsmash since it doesn't find the hash, removing the S after the ftilt/fsmash animation name allows Forge to load the script and do hitbox visualization

Add command grabboxes

---

Smash Forge/CharacterParamManager.cs
Smash Forge/Filetypes/Models/VBN.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/GUI/MainForm.cs

- Open Character dialogue now syncs, populates and refreshes the bone control.
- Fixed (harmless) memory leak when opening files (new ModelContainer being made each time)
- Added event 0x2F08F54F ("Delete_Catch_Collision" by ID) which is used mainly in tether grabs like ZSS and Link to remove a particular grab box halfway through.
- Fixed bone / joint table indexing between the NUD bones and the joint table bones such that bones from joint tables 1 and above are actually found properly.
- Added hurtbox rendering for circular hurtboxes (see: Bowser Jr's clown body)

Fix hitbox/hurtbox rendering for joint table bones

---

Smash Forge/Filetypes/Animation/OMO.cs

W value of some types of KeyNode was being calculated as NaN. This broke entire trees of models affected (the case that found this was ZSS' paralyser gun model/animation combo).

Fixed bug with OMO parsing

---

Smash Forge/GUI/Editors/RenderTools.cs
Smash Forge/GUI/Editors/VBNViewport.Designer.cs
Smash Forge/GUI/Editors/VBNViewport.cs

Before this commit SmashForge shows a giant 100f unit radius sphere around the
model instead of showing the hurtbox cylinders.
Added 8 bits of stencil buffer to the GLControl. Note that this makes
hurtboxes and bones mutually exclusive right now since they don't play
nicely with depth/stencil.

Fix hurtbox display

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Melee/DAT.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Editors/LVD Editor/LVDList.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/GUI/MainForm.cs
Smash Forge/param_labels/Render_Param.ini
Smash Forge/param_labels/crazy_side_param.ini
Smash Forge/param_labels/item_stage_gen_param.ini
Smash Forge/param_labels/ui_movie_db.ini

I have significantly changed the class definitions and reading of LVD.
- Base class 'LVDEntry' (of which LVD objects derive) is fleshed out to be the base of LVD objects. This enables objects to read/write their bone name and start position (previously only done for collisions).
- Implemented 'CLIFF' objects for collisions. Cliffs are now read and written, but they remain unaccessible in the GUI.
- Separated spawns and respawns to use a separate class, 'Spawn'. General points are now 'GeneralPoint', a derivative of 'LVDGeneralShape'. The 'Point' class remains in order to not break a lot of code that is using it.
- Some general re-organizing and formatting.
I have also added a parameter label .ini file, and modified two others: one for typos and the other for new values.

Cleanup for LVD, add CLIFFs and improve data preservation; Add/modify param labels

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Editors/LVD Editor/LVDList.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/GUI/MainForm.cs

I have done some more work on LVD, primarily for shapes and points.
- Add new classes to be used by general shapes and damage shapes ('GeneralShape' and 'DamageShape', respectively). The different types of these respective objects can be handled identically in i/o, so they are better off with one object type. Implementations can decide how to handle these objects by their 'type' member, and I have updated existing code to do so.
- Improve reading of general shapes and damage shapes, and add writing to the latter. Damage shapes are no longer lost when saving, however they remain uneditable in the GUI.
- Remove categorization of GeneralPoint as general shapes. Currently, I can find no example of an LVD that has general points in its general shapes. Previously, the general shapes list was …

Cleanup for LVD shapes and points, bugfixes

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Menus/DAEImportSettings.cs

I've made some relatively minor changes.
- Render cliffs of LVD collisions in the viewport. Each cliff is now rendered in the viewport, with a white line at its position and a blue line representing its angle.
- Add code for guessing passthrough angles on LVD collisions (unused). There was code present in a button function for the LVD GUI for (an attempt at) guessing the passthrough angles of all lines in a collision. I commented out this code and added some new code (math from jam1garner's old python lvd tool; it seems he wrote most of the lvd code for Forge, too), which seems like it could work. The button this code is attached to was and still is disabled.
- Modify DAE importing option 'Divide vertex color by 2'. The previous code halved all four channels of the color (RGBA), now it …

Render LVD cliffs, tweak DAE import option

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Models/NUD.cs
Smash Forge/GUI/Editors/NUDMaterialEditor.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/GUI/Menus/RenderSettings.Designer.cs

- Move rendering of LVD objects to functions. This makes the rendering of LVD objects more accessible. It also fixes a bug in which objects could be rendered differently based on which types of objects are being rendered, due to GL variables that weren't being set consistently.
- Rename render settings checkbox 'Render General Points' to 'Render General Shapes and Points', fix it toggling improperly. The checkbox would previously only toggle the rendering state after another checkbox was toggled, due to a missing event call.
- Update NUD material cull modes. Previously, the value 0x205 was listed as the option for 'Cull Outside' (listed as 'Cull Front'), however this value is just another equivalent to 'Cull None'. I removed it and added the value 0x404 as the option for 'Cull Outside' …

LVD rendering and NUD tweaks

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Models/NUD.cs
Smash Forge/GUI/Editors/VBNViewport.cs

- Update NUD to calculate bounding spheres instead of bounding boxes. From my tests, the new calculations can often give a result much closer (nearly identical) to the original game's values for vanilla models than the old calculation did, at least from checking for the lower radius of two. The previous calculation could also result in such things as a radius of 0.
- Update LVD rendering to account for start position of all objects. Previously, only collisions would factor in their start position during rendering, but since there is now handling of the start position for all object types, I have updated the rendering functions to properly account for it. This fixes some objects rendering in the wrong positions (mainly cliffs).

Update NUD bound calculations; Update LVD rendering

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Models/NUD.cs
Smash Forge/GUI/Editors/NUDMaterialEditor.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/Rendering/RenderTools.cs

- Fix NUD material property deletion being non-functional. A mistake (caused by a copy-paste) made it so that this feature would only function if the material's amount of textures greater than one, as opposed to its amount of properties.
- Remove defining of GL color from render function 'drawCubeWireframe'. This function contained a statement to set the color to red, which would override attempts to set the color by code using the function, thus making the resulting cube always red. Now the color can be set without being overriden, which has enabled NUD bounding boxes to render with the colors they were intended to.

Minor bugfixes

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.Designer.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Editors/LVD Editor/LVDList.cs

I have made a lot of changes to the GUI for working with LVDs.
- All LVD objects now have available the start position and bone name fields, as they are common to all types.
- Cliffs are now available in the GUI. Currently, they can be deleted, or have their global fields changed.
- There is now the option in the context menu of the 'Collisions' node to generate cliffs from scratch for all collisions in the LVD.
- Name and subname fields now limit the length of the input string to the maximum they are allowed.
- General points now have Z position available.
- General points in general shapes now have more fitting fields available, instead of using the same fields as general rectangles.
- The context menu for adding general shapes now works properly.
- Update the default names of various …

LVD UI rework

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Melee/DAT.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.Designer.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Editors/LVD Editor/LVDList.cs
Smash Forge/GUI/Editors/VBNViewport.cs
Smash Forge/Smash Forge.csproj

Continued work on LVD:
- Cliffs are now fully editable in the GUI.
- Cliff generation now accounts for start position and bone name of parent collisions.
- New 'LVDShape' class replaces previous shape classes, 'Section' class, and 'EnmSection' class entirely. I realized that all of these things are using the same structure for their data.
- ItemSpawner now sets its ID on initialization (to the one most commonly used).
- Add properties to CollisionMaterial class, to allow easier access to collision flags.
- Update shape rendering. GeneralShapes are still rendered in pink, but EnemyGenerators now render their shapes in white and orange (and as the correct shapes, too).
- Cleanup code for adding and removing vertices on a collision. It is less/not prone to exceptions now.
- DamageShapes and …

LVD UI rework Part 2

---

Smash Forge/Filetypes/LVD.cs
Smash Forge/Filetypes/Textures/DDS.cs
Smash Forge/Filetypes/Textures/NUT.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.Designer.cs
Smash Forge/GUI/Editors/LVD Editor/LVDEditor.cs
Smash Forge/GUI/Menus/PolygonFormatEditor.cs
Smash Forge/param_labels/stage_param.ini

- NUT fixes
- Fixed importing of some DXT5 textures causing a game crash. For DXT5 textures that are not square, mipmap amount will now be limited to the maximum amount that will not cause a game crash. (Thanks to TNN, mOatles and DSX8 for assisting with this issue.)
- Added importing of DXT3 texture format.
- Fixed importing of RGBA texture format.
- Fixed exporting of textures often resulting in partially-broken DDS files.
- Fixed error upon opening certain nut files (e.g. "Baramoku" trophy). (Thanks to SMG for reporting this issue.)
- LVD fixes
- Fixed error upon adding vertices to a collision that has none.
- Updated collision physics material list. Several new types have been added, based on data from Brawl. (Thanks to [StageBox](https://github.com/soopercool101/stagebox)'s code for …

NUT and LVD fixes

---

Smash Forge/Filetypes/Melee/DAT.cs
Smash Forge/Filetypes/Textures/DDS.cs
Smash Forge/Filetypes/Textures/NUT.cs
Smash Forge/GUI/Editors/NUTEditor.cs
Smash Forge/GUI/Editors/UIPreview.cs
Smash Forge/IO/FileOutput.cs

- NUT refactoring:
- New class, ``TextureSurface``, and new ``NutTexture`` member, ``public List<TextureSurface> surfaces``, to replace the old ``public List<byte[]> mipmaps``. ``TextureSurface`` contains an equivalent member to ``mipmaps``. Image data is now accessed as ``texture.surfaces[i].mipmaps[j]``, where there is 1 surface for most textures and 6 surfaces for cubemaps.
- New functions, ``void swapChannelOrderUp()`` and ``void swapChannelOrderDown()``, which replace certain code snippets of the IO functions. They are intended to be called only from within said IO functions.
- Refactor GTX NUT IO code to partially add support for cubemaps.
- Changed integer type and/or signage for several variables throughout the NUT IO code.
- FileOutput
- New functions: ``void writeUShort(ushort …

NUT IO and class updates

---

Smash Forge/Filetypes/Animation/MTA.cs
Smash Forge/Filetypes/Application/Config.cs
Smash Forge/Filetypes/Models/ModelContainer.cs
Smash Forge/Filetypes/Models/NUD.cs
Smash Forge/GUI/Editors/LVD Editor/LVDList.cs
Smash Forge/GUI/Editors/MeshList.Designer.cs
Smash Forge/GUI/Editors/MeshList.cs
Smash Forge/GUI/MainForm.cs
Smash Forge/GUI/Menus/DAEImportSettings.cs
Smash Forge/GUI/Menus/RenderSettings.cs
Smash Forge/GUI/ModelViewport.cs
Smash Forge/Runtime.cs

- LVD bugfixes:
- Fixed context menu not appearing for entries other than collisions.
- The viewport tab now displays the file name of the lvd file, rather than the full path of it.
- MTA updates to class members:
- One of the unknowns in ``MatData`` has been renamed to ``animType``, and an enum has been added representing its possible values.
- ``startFrame`` and ``endFrame`` are now read and stored. When compiling an MTA, they are set automatically, as they are not included in the decompilation.
- Renamed ``numFrames`` in the ``MTA`` class to ``frameCount``.
- In the context of NUD, rename "bounding box" to "bounding sphere". I have reviewed each occurence that has been replaced to check that nothing is broken.

Bugfixes; rename bounding box to bounding sphere

---

Smash Forge/ACMDScript.cs
Smash Forge/GUI/Editors/VariableList.cs

I also made a commit to SALT to fix an issue where a couple commands args weren't written as a FighterVariable type. Until that's updated there will be a couple of instances where Forge can still crash but it happens on far fewer moves than where the normal crash happens.
On another note, I'm not sure if SortedList using FighterVariable as the Key will cause any issues given that there isn't really a comparer defined for FighterVariable. It might also just not matter

Fix issue where SALT update caused cast errors

---

Smash Forge/Filetypes/BFRES/BFRES_Main.cs
Smash Forge/Filetypes/BFRES/Switch/BNTX.cs
Smash Forge/Filetypes/BFRES/WiiU/FTEX.cs
Smash Forge/Filetypes/Textures/DDS.cs
Smash Forge/GUI/Editors/BNTXEditor.cs
Smash Forge/GUI/MainForm.cs
Smash Forge/GUI/ModelViewport.cs

This specifically fixes FTEX textures not binding and the containers being ran as null (would break switch bfres from opening) and uses the changed Texture2D constructors now. Mip maps are not implemented yet but is planned in a later PR. 
Edit: wait till i fix up bntx editor for merging.

Fix bfres textures from displaying

---

Smash Forge/ACMDScript.cs

Once SALT gets updated (with a PR I just made to it), there shouldn't be any more problems with crashing moveset viewing due to FighterVariable
One more note: I removed a couple bad cases which didn't use variables at all (they were mislabeled) and added some code in one case which may or may not even do anything, but at least it's more accurate technically

Fix more ACMD variable cast crashes

---

Smash Forge/Filetypes/Textures/DDS.cs

A trivial change to texture importing which fixes a game-crashing NUT when importing non-square DXT3 textures with mipmaps. The DXT3 format is the same size as DXT5 and so had the same problem DXT5 had, which is fixed by limiting the number of mipmaps imported.

DXT3 texture importing fix

---

Smash Forge/Filetypes/Application/MaterialXML.cs
Smash Forge/Filetypes/Models/Nuds/Material.cs
Smash Forge/Filetypes/Models/Nuds/NUD.cs
Smash Forge/Filetypes/Models/Nuds/NudEnums.cs
Smash Forge/Filetypes/Models/Nuds/NudRenderMesh.cs
Smash Forge/GUI/Editors/NUDMaterialEditor.Designer.cs
Smash Forge/GUI/Editors/NUDMaterialEditor.cs

I have reworked the alpha function material value. Forge has handled it as two separate values, but in fact it's only one. I've updated the IO code accordingly, as well as the material editor and material XML.
- Materials have a new value called `AlphaFunc`. The two previous values, `AlphaTest` and `AlphaFunction`, are still supported via properties, but should not be used.
- All alpha functions should now render correctly, including Pokken.
- Material editor:
- Always show the alpha function dropdown. The alpha test checkbox has been removed.
- Added the alpha function values used in Pokken.
- Material XML:
- Export the value `alphaFunc`, instead of `AlphaFunc` and `AlphaTest`.
- Renamed `RefAlpha` and `cullmode`, to `alphaRef` and `cullMode`, respectively, for consistency with other …

Rework alpha function

---

Smash Forge/Filetypes/Models/Nuds/Material.cs
Smash Forge/Filetypes/Models/Nuds/NUD.cs
Smash Forge/Filetypes/Models/Nuds/Polygon.cs

I've added support for a NUD vertex format flag, wherein UV data is stored as floats rather than half-floats. It's used in the Wangan Midnight games. Thanks to @wood5578 for ongoing collaboration; bringing this particular issue to my attention, providing files, and testing changes.
- Added a new polygon attribute, `uvType`, and a new enum, `UVTypes`
- Updated the NUD IO code accordingly
- It also now uses more abstractions, such as the new attributes and enums, rather than magic numbers.
- Fixed a potential issue with the deprecated material attributes, `AlphaTest` and `AlphaFunction`, not matching their prior implementation, which could have resulted in erroneous behavior when importing old XMLs.

Add NUD float UV support

---

Smash Forge/Filetypes/Models/Nuds/Polygon.cs
Smash Forge/GUI/Menus/PolygonFormatEditor.Designer.cs
Smash Forge/GUI/Menus/PolygonFormatEditor.cs

I have updated the PolygonFormatEditor menu to add new features, improve existing ones, and clean up the code.
- Reordered field options to be more logical. Options are ordered by the size of the data type they correspond to, which also happens to prioritise the options most commonly used in Smash.
- Added a new field for vertex color type. (Replaces a checkbox.)
- Added a new field for UV type.
- Added a new field for face type.
- Added conversions between triangles and triangle strips. The conversion to triangle strips currently doesn't have an algorithm to make proper strips, so it simply converts the triangles directly into individual strips.

New additions to PolygonFormatEditor menu

---

Smash Forge/Filetypes/Application/MaterialXML.cs
Smash Forge/Filetypes/Models/Nuds/Mesh.cs
Smash Forge/Filetypes/Models/Nuds/NUD.cs

I have made some changes to NUD.
- Bounding spheres:
- Simplify bounding sphere calculations. It still yields results on par with vanilla values.
- A mesh's `boundingSphere` is now 4 values rather than 8, as the NUD format contains duplicate information for these values, which is now ignored.
- Update `sortBias` value:
- It's now read and written correctly within the file, and treated as a float rather than an integer.
- Remove code for determining a mesh's sort bias from its name, as it is no longer needed.
- Minor style changes to material XML code.

NUD bounding sphere updates
